local M = {}

M.overrides = {
    mocha = {
        text = "#cdd6f4",
        subtext1 = "#bac2de",
        subtext0 = "#a6adc8",
        overlay1 = "#7f849c",
        overlay0 = "#6c7086",
        surface1 = "#45475a",
        surface0 = "#313244",
        base = "#1e1e2e",
        mantle = "#181825",
        crust = "#11111b",

        pink = "#f5c2e7",
        mauve = "#cba6f7",
        red = "#f37b88",
        maroon = "#db909c",
        peach = "#fab387",
        yellow = "#f9e2af",
        green = "#a6e3a1",
        teal = "#94e2d5",
        sky = "#80cafb",
        blue = "#89a4fa",
        lavender = "#b4befe",
    },
    latte = {
        text = "#1e1e2f",
        subtext1 = "#3c3f57",
        subtext0 = "#5c5f75",
        overlay1 = "#8c8fa1",
        overlay0 = "#acb0be",
        surface1 = "#bcc0cc",
        surface0 = "#ccd0da",
        base = "#eff1f5",
        mantle = "#e6e9ef",
        crust = "#dce0e8",

        pink = "#da56ab",
        mauve = "#7809af",
        red = "#c20f19",
        maroon = "#a64553",
        peach = "#ee6419",
        yellow = "#df8e1d",
        green = "#40902b",
        teal = "#209fb5",
        sky = "#0495e5",
        blue = "#0046a9",
        lavender = "#6257bd",
    },
}

M.highlight = function(colors)
    return {
        -- Dashboard-specific highlights
        DashNvim = { fg = colors.blue, bg = "NONE", bold = true },
        DashHelp = { fg = colors.overlay2, bg = "NONE" },
        DashFoot = { fg = colors.overlay0, bg = "NONE" },
        -- Quality of Life stuff
        DiagnosticError = { fg = colors.red, bold = true, style = {} },
        DiagnosticWarn = { fg = colors.peach, bold = true, style = {} },
        DiagnosticHint = { fg = colors.teal, bold = true, style = {} },
        DiagnosticInfo = { fg = colors.sky, bold = true, style = {} },
        LineNr = { fg = colors.base },
        LineNrAbove = { fg = colors.subtext1 },
        LineNrBelow = { fg = colors.subtext1 },
        FoldMarker = { bg = colors.green, fg = colors.crust },
        FoldedText = { bg = colors.surface0, fg = colors.text },
        Folded = { fg = colors.text, bg = "NONE" },
        Conceal = { fg = colors.lavender, bg = colors.base },
        ["@markup.italic"] = { fg = colors.text, style = { "italic" } },
        ["@markup.strong"] = { fg = colors.text, bold = true },
        -- Statusline stuff
        HeaderModeNO = { fg = colors.crust, bg = colors.subtext0, bold = true },
        HeaderModeEX = { fg = colors.crust, bg = colors.blue, bold = true },
        HeaderModeVI = { fg = colors.crust, bg = colors.lavender, bold = true },
        HeaderModeVL = { fg = colors.crust, bg = colors.lavender, bold = true },
        HeaderModeVB = { fg = colors.crust, bg = colors.lavender, bold = true },
        HeaderModeIN = { fg = colors.crust, bg = colors.peach, bold = true },
        HeaderModeRE = { fg = colors.crust, bg = colors.maroon, bold = true },
        HeaderBlank = { fg = colors.base, bg = colors.base },
        HeaderWeak = { fg = colors.subtext0, bg = colors.base },
        HeaderSimple = { fg = colors.text, bg = colors.base },
        HeaderSolid = { fg = colors.text, bg = colors.base, bold = true },
        HeaderSidebar = { fg = colors.mantle, bg = colors.mantle },
        StatusLine = { fg = colors.surface2, bg = colors.base },
        StatusLineNC = { fg = colors.surface2, bg = colors.base },
        StatusCol = { bg = colors.surface0, bold = true },
        TabLine = { fg = colors.surface2, bg = colors.base },
        TabLineSel = { fg = colors.green, bg = colors.crust, bold = true },
        TabLineFill = { fg = colors.surface2, bg = colors.base },
        WinSeparator = { fg = colors.overlay2, bg = colors.base },
        WinBar = { fg = colors.text, bg = colors.base },
        -- Telescope Highlights
        TelescopeMatching = { fg = colors.flamingo },
        TelescopeSelection = { fg = colors.flamingo, bg = colors.surface0, bold = true },
        TelescopeSelectionCaret = { fg = colors.surface0, bg = colors.surface0 },
        TelescopePromptPrefix = { fg = colors.maroon, bg = colors.base },
        TelescopePromptNormal = { bg = colors.base },
        TelescopeResultsNormal = { bg = colors.base },
        TelescopePreviewNormal = { bg = colors.base },
        TelescopePromptBorder = { bg = colors.base, fg = colors.surface1 },
        TelescopeResultsBorder = { bg = colors.base, fg = colors.subtext0 },
        TelescopePreviewBorder = { bg = colors.base, fg = colors.surface0 },
        TelescopePromptTitle = { bg = colors.blue, fg = colors.crust },
        TelescopeResultsTitle = { bg = colors.red, fg = colors.crust },
        TelescopePreviewTitle = { bg = colors.green, fg = colors.crust },
        -- Completion Icons
        CmpItemAbbrDeprecated = { fg = colors.surface1, bg = "NONE", strikethrough = true, },
        CmpItemAbbrMatch = { fg = colors.blue, bg = "NONE", bold = true, },
        CmpItemAbbrMatchFuzzy = { fg = colors.blue, bg = "NONE", bold = true, },
        CmpItemMenu = { fg = colors.mauve, bg = "NONE", italic = true, },
        CmpItemKindCopilot = { fg = colors.green, bg = colors.crust, },
        CmpItemKindField = { fg = colors.crust, bg = colors.red, },
        CmpItemKindProperty = { fg = colors.crust, bg = colors.red, },
        CmpItemKindEvent = { fg = colors.crust, bg = colors.red, },
        CmpItemKindText = { fg = colors.crust, bg = colors.green, },
        CmpItemKindEnum = { fg = colors.crust, bg = colors.green, },
        CmpItemKindKeyword = { fg = colors.crust, bg = colors.green, },
        CmpItemKindConstant = { fg = colors.crust, bg = colors.green, },
        CmpItemKindConstructor = { fg = colors.crust, bg = colors.green, },
        CmpItemKindReference = { fg = colors.crust, bg = colors.green, },
        CmpItemKindFunction = { fg = colors.crust, bg = colors.mauve, },
        CmpItemKindStruct = { fg = colors.crust, bg = colors.mauve, },
        CmpItemKindClass = { fg = colors.crust, bg = colors.mauve, },
        CmpItemKindModule = { fg = colors.crust, bg = colors.mauve, },
        CmpItemKindOperator = { fg = colors.crust, bg = colors.mauve, },
        CmpItemKindVariable = { fg = colors.text, bg = colors.surface0, },
        CmpItemKindFile = { fg = colors.text, bg = colors.surface0, },
        CmpItemKindUnit = { fg = colors.crust, bg = colors.peach, },
        CmpItemKindSnippet = { fg = colors.crust, bg = colors.peach, },
        CmpItemKindFolder = { fg = colors.crust, bg = colors.peach, },
        CmpItemKindMethod = { fg = colors.crust, bg = colors.blue, },
        CmpItemKindValue = { fg = colors.crust, bg = colors.blue, },
        CmpItemKindEnumMember = { fg = colors.crust, bg = colors.blue, },
        CmpItemKindInterface = { fg = colors.crust, bg = colors.teal, },
        CmpItemKindColor = { fg = colors.crust, bg = colors.teal, },
        CmpItemKindTypeParameter = { fg = colors.crust, bg = colors.teal, },
        -- Vimtex highlights
        texCmd = { fg = colors.blue },
        texArg = { fg = colors.peach },
        texCSectionArg = { fg = colors.sky, bold = true },
        texCmdCSection = { fg = colors.sky, bold = true },
        texCSubsectionArg = { fg = colors.green, bold = true },
        texCmdCSubsection = { fg = colors.green, bold = true },
        texCSubsubsectionArg = { fg = colors.teal, bold = true },
        texCmdCSubssubection = { fg = colors.teal, bold = true },
    }
end

return M
