local M = {}

M.overrides = {
    latte = {
        pink = "#da56ab",
        mauve = "#7819cf",
        red = "#c20f19",
        maroon = "#c64553",
        peach = "#ee6419",
        yellow = "#df8e1d",
        green = "#40902b",
        teal = "#078289",
        sky = "#0495e5",
        sapphire = "#209fb5",
        blue = "#0e56c9",
        lavender = "#6257bd",
    },
}

M.highlight = function(colors)
    return {
        -- Dashboard-specific highlights
        DashNvim = { fg = colors.blue, bg = "NONE", bold = true },
        DashLink = { fg = colors.overlay2, bg = "NONE", underline = true },
        DashFoot = { fg = colors.overlay0, bg = "NONE" },
        -- Quality of Life stuff
        DiagnosticError = { fg = colors.red, bold = true, style = {} },
        DiagnosticWarn = { fg = colors.peach, bold = true, style = {} },
        DiagnosticHint = { fg = colors.teal, bold = true, style = {} },
        DiagnosticInfo = { fg = colors.sky, bold = true, style = {} },
        LineNr = { fg = colors.base },
        LineNrAbove = { fg = colors.surface2 },
        LineNrBelow = { fg = colors.surface2 },
        FoldMarker = { bg = colors.green, fg = colors.crust },
        FoldedText = { bg = colors.surface0, fg = colors.text },
        Folded = { fg = colors.text },
        Conceal = { fg = colors.lavender, bg = colors.base },
        -- Statusline stuff
        WinSeparator = { fg = colors.subtext0, bg = colors.base },
        WinBar = { fg = colors.subtext0, bg = colors.base },
        HeaderBlank = { fg = colors.base, bg = colors.base },
        HeaderWeak = { fg = colors.subtext0, bg = colors.base },
        HeaderSimple = { fg = colors.text, bg = colors.base },
        HeaderSolid = { fg = colors.text, bg = colors.base, bold = true },
        HeaderSidebar = { fg = colors.mantle, bg = colors.mantle },
        StatusLine = { fg = colors.surface2, bg = colors.base },
        StatusLineNC = { fg = colors.surface2, bg = colors.base },
        TabLine = { fg = colors.surface2, bg = colors.base },
        TabLineSel = { fg = colors.green, bg = colors.crust, bold = true },
        TabLineFill = { fg = colors.surface2, bg = colors.base },
        -- Telescope Highlights
        TelescopeMatching = { fg = colors.flamingo },
        TelescopeSelection = { fg = colors.flamingo, bg = colors.surface0, bold = true },
        TelescopeSelectionCaret = { fg = colors.surface0, bg = colors.surface0 },
        TelescopePromptPrefix = { fg = colors.maroon, bg = colors.crust },
        TelescopePromptNormal = { bg = colors.crust },
        TelescopeResultsNormal = { bg = colors.base },
        TelescopePreviewNormal = { bg = colors.base },
        TelescopePromptBorder = { bg = colors.base, fg = colors.crust },
        TelescopeResultsBorder = { bg = colors.base, fg = colors.subtext0 },
        TelescopePreviewBorder = { bg = colors.base, fg = colors.subtext0 },
        TelescopePromptTitle = { bg = colors.blue, fg = colors.crust },
        TelescopeResultsTitle = { bg = colors.red, fg = colors.crust },
        TelescopePreviewTitle = { bg = colors.green, fg = colors.crust },
        -- Completion Icons
        CmpItemAbbrDeprecated = { fg = colors.surface1, bg = "NONE", strikethrough = true, },
        CmpItemAbbrMatch = { fg = colors.blue, bg = "NONE", bold = true, },
        CmpItemAbbrMatchFuzzy = { fg = colors.blue, bg = "NONE", bold = true, },
        CmpItemMenu = { fg = colors.mauve, bg = "NONE", italic = true, },
        CmpItemKindCopilot = { fg = colors.green, bg = colors.crust, },
        CmpItemKindField = { fg = colors.crust, bg = colors.red, },
        CmpItemKindProperty = { fg = colors.crust, bg = colors.red, },
        CmpItemKindEvent = { fg = colors.crust, bg = colors.red, },
        CmpItemKindText = { fg = colors.crust, bg = colors.green, },
        CmpItemKindEnum = { fg = colors.crust, bg = colors.green, },
        CmpItemKindKeyword = { fg = colors.crust, bg = colors.green, },
        CmpItemKindConstant = { fg = colors.crust, bg = colors.green, },
        CmpItemKindConstructor = { fg = colors.crust, bg = colors.green, },
        CmpItemKindReference = { fg = colors.crust, bg = colors.green, },
        CmpItemKindFunction = { fg = colors.crust, bg = colors.mauve, },
        CmpItemKindStruct = { fg = colors.crust, bg = colors.mauve, },
        CmpItemKindClass = { fg = colors.crust, bg = colors.mauve, },
        CmpItemKindModule = { fg = colors.crust, bg = colors.mauve, },
        CmpItemKindOperator = { fg = colors.crust, bg = colors.mauve, },
        CmpItemKindVariable = { fg = colors.text, bg = colors.surface0, },
        CmpItemKindFile = { fg = colors.text, bg = colors.surface0, },
        CmpItemKindUnit = { fg = colors.crust, bg = colors.peach, },
        CmpItemKindSnippet = { fg = colors.crust, bg = colors.peach, },
        CmpItemKindFolder = { fg = colors.crust, bg = colors.peach, },
        CmpItemKindMethod = { fg = colors.crust, bg = colors.blue, },
        CmpItemKindValue = { fg = colors.crust, bg = colors.blue, },
        CmpItemKindEnumMember = { fg = colors.crust, bg = colors.blue, },
        CmpItemKindInterface = { fg = colors.crust, bg = colors.teal, },
        CmpItemKindColor = { fg = colors.crust, bg = colors.teal, },
        CmpItemKindTypeParameter = { fg = colors.crust, bg = colors.teal, },
        -- Vimtex highlights
        texCmd = { fg = colors.blue },
        texArg = { fg = colors.peach },
        texCSectionArg = { fg = colors.sky, bold = true },
        texCmdCSection = { fg = colors.sky, bold = true },
        texCSubsectionArg = { fg = colors.green, bold = true },
        texCmdCSubsection = { fg = colors.green, bold = true },
        texCSubsubsectionArg = { fg = colors.teal, bold = true },
        texCmdCSubssubection = { fg = colors.teal, bold = true },
    }
end

return M
